spring:
  datasource:
    url: jdbc:mysql://localhost:3306/griden_db
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org:
      springframework:
        security=DEBUG:

jwt:
  secret: Spasi_HospadiSpasi_HospadiSpasi_HospadiSpasi_Hospadi

springdoc:
  swagger-ui:
    path: /swagger-ui
